apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: react-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # Access via http://node-ip:30080
  type: NodePort