apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-backend
  labels:
    app: nodejs-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-backend
  template:
    metadata:
      labels:
        app: nodejs-backend
    spec:
      containers:
      - name: nodejs-backend
        image: firas444/pfe-backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: MONGODB_URI
          value: "mongodb://admin:password123@mongodb-service:27017/Order-webapp?authSource=admin"
        - name: PORT
          value: "3000"
        command: ["npm", "start"]  # Adjust based on your package.json
        # args: ["npm install && npm start"]
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"